from infografia import IInfografia
from marcacao import IMarcacao
from pauta import IPauta
from servico import IServico
from santinho import ISantinho
from especial import IEspecial
from evento import IEvento
from texto import ITexto
from chamada import IChamada
from criacao import ICriacao